#!/bin/sh

SERVICE_NAME="glimpse-probe"
USER_NAME="glimpse"

# Source debconf library.
. /usr/share/debconf/confmodule

set -x
set -e

case "$1" in
    configure)
    adduser --system --group --quiet $USER_NAME || true

    if command -v service >/dev/null 2>&1; then
        service $SERVICE_NAME start || true
    fi

    if command -v systemctl >/dev/null 2>&1; then
        systemctl start $SERVICE_NAME || true
    fi
    ;;
esac

#DEBHELPER#
